export const GROUPS: Record<string, string[]> = {
  A: ['Mexico', 'South Africa', 'South Korea', 'Czechia'],
  B: ['Canada', 'Bosnia & Herzegovina', 'Qatar', 'Switzerland'],
  C: ['Brazil', 'Morocco', 'Haiti', 'Scotland'],
  D: ['United States', 'Paraguay', 'Australia', 'Turkey'],
  E: ['Germany', 'Curacao', 'Ivory Coast', 'Ecuador'],
  F: ['Netherlands', 'Japan', 'Sweden', 'Tunisia'],
  G: ['Belgium', 'Egypt', 'Iran', 'New Zealand'],
  H: ['Spain', 'Cape Verde', 'Saudi Arabia', 'Uruguay'],
  I: ['France', 'Senegal', 'Iraq', 'Norway'],
  J: ['Argentina', 'Algeria', 'Austria', 'Jordan'],
  K: ['Portugal', 'DR Congo', 'Uzbekistan', 'Colombia'],
  L: ['England', 'Croatia', 'Ghana', 'Panama'],
}

// [emoji, 3-letter code, FIFA rank]
export const TEAM: Record<string, [string, string, number]> = {
  'Mexico':               ['🇲🇽', 'MEX', 15],
  'South Africa':         ['🇿🇦', 'RSA', 56],
  'South Korea':          ['🇰🇷', 'KOR', 23],
  'Czechia':              ['🇨🇿', 'CZE', 42],
  'Canada':               ['🇨🇦', 'CAN', 27],
  'Bosnia & Herzegovina': ['🇧🇦', 'BIH', 70],
  'Qatar':                ['🇶🇦', 'QAT', 37],
  'Switzerland':          ['🇨🇭', 'SUI', 17],
  'Brazil':               ['🇧🇷', 'BRA',  5],
  'Morocco':              ['🇲🇦', 'MAR', 11],
  'Haiti':                ['🇭🇹', 'HAI', 84],
  'Scotland':             ['🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'SCO', 36],
  'United States':        ['🇺🇸', 'USA', 14],
  'Paraguay':             ['🇵🇾', 'PAR', 39],
  'Australia':            ['🇦🇺', 'AUS', 26],
  'Turkey':               ['🇹🇷', 'TUR', 25],
  'Germany':              ['🇩🇪', 'GER',  9],
  'Curacao':              ['🇨🇼', 'CUW', 82],
  'Ivory Coast':          ['🇨🇮', 'CIV', 41],
  'Ecuador':              ['🇪🇨', 'ECU', 24],
  'Netherlands':          ['🇳🇱', 'NED',  7],
  'Japan':                ['🇯🇵', 'JPN', 18],
  'Sweden':               ['🇸🇪', 'SWE', 44],
  'Tunisia':              ['🇹🇳', 'TUN', 40],
  'Belgium':              ['🇧🇪', 'BEL',  8],
  'Egypt':                ['🇪🇬', 'EGY', 34],
  'Iran':                 ['🇮🇷', 'IRN', 20],
  'New Zealand':          ['🇳🇿', 'NZL', 89],
  'Spain':                ['🇪🇸', 'ESP',  1],
  'Cape Verde':           ['🇨🇻', 'CPV', 68],
  'Saudi Arabia':         ['🇸🇦', 'KSA', 60],
  'Uruguay':              ['🇺🇾', 'URU', 16],
  'France':               ['🇫🇷', 'FRA',  3],
  'Senegal':              ['🇸🇳', 'SEN', 19],
  'Iraq':                 ['🇮🇶', 'IRQ', 58],
  'Norway':               ['🇳🇴', 'NOR', 29],
  'Argentina':            ['🇦🇷', 'ARG',  2],
  'Algeria':              ['🇩🇿', 'ALG', 35],
  'Austria':              ['🇦🇹', 'AUT', 22],
  'Jordan':               ['🇯🇴', 'JOR', 66],
  'Portugal':             ['🇵🇹', 'POR',  6],
  'DR Congo':             ['🇨🇩', 'COD', 53],
  'Uzbekistan':           ['🇺🇿', 'UZB', 57],
  'Colombia':             ['🇨🇴', 'COL', 13],
  'England':              ['🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'ENG',  4],
  'Croatia':              ['🇭🇷', 'CRO', 10],
  'Ghana':                ['🇬🇭', 'GHA', 72],
  'Panama':               ['🇵🇦', 'PAN', 30],
}

// Uppercase ISO-2 codes for country-flag-icons
export const CODE2: Record<string, string> = {
  'Mexico':               'MX',
  'South Africa':         'ZA',
  'South Korea':          'KR',
  'Czechia':              'CZ',
  'Canada':               'CA',
  'Bosnia & Herzegovina': 'BA',
  'Qatar':                'QA',
  'Switzerland':          'CH',
  'Brazil':               'BR',
  'Morocco':              'MA',
  'Haiti':                'HT',
  'Scotland':             'GB-SCT',
  'United States':        'US',
  'Paraguay':             'PY',
  'Australia':            'AU',
  'Turkey':               'TR',
  'Germany':              'DE',
  'Curacao':              'CW',
  'Ivory Coast':          'CI',
  'Ecuador':              'EC',
  'Netherlands':          'NL',
  'Japan':                'JP',
  'Sweden':               'SE',
  'Tunisia':              'TN',
  'Belgium':              'BE',
  'Egypt':                'EG',
  'Iran':                 'IR',
  'New Zealand':          'NZ',
  'Spain':                'ES',
  'Cape Verde':           'CV',
  'Saudi Arabia':         'SA',
  'Uruguay':              'UY',
  'France':               'FR',
  'Senegal':              'SN',
  'Iraq':                 'IQ',
  'Norway':               'NO',
  'Argentina':            'AR',
  'Algeria':              'DZ',
  'Austria':              'AT',
  'Jordan':               'JO',
  'Portugal':             'PT',
  'DR Congo':             'CD',
  'Uzbekistan':           'UZ',
  'Colombia':             'CO',
  'England':              'GB-ENG',
  'Croatia':              'HR',
  'Ghana':                'GH',
  'Panama':               'PA',
}

// Round-robin match pairs within each group (indices into the 4-team array)
export const PAIRS: [number, number][] = [
  [0, 1], [2, 3], [0, 2], [1, 3], [0, 3], [1, 2],
]

// R32 bracket skeleton — hand-verified, no same-group clashes before QF
export const R32: [string, string][] = [
  ['1H', 'T'], ['2C', '2F'], ['1A', 'T'], ['1B', '2E'],
  ['1I', 'T'], ['2G', '2K'], ['1C', 'T'], ['1D', '2A'],
  ['1L', 'T'], ['2B', '2D'], ['1E', 'T'], ['1F', '2J'],
  ['1J', 'T'], ['2H', '2L'], ['1K', 'T'], ['1G', '2I'],
]

// Third-place wildcard slot definitions [R32 slot index, groups to avoid]
export const THIRD_SLOTS: [number, string[]][] = [
  [0,  ['H', 'C', 'F']],
  [2,  ['A', 'B', 'E']],
  [4,  ['I', 'G', 'K']],
  [6,  ['C', 'D', 'A']],
  [8,  ['L', 'B', 'D']],
  [10, ['E', 'F', 'J']],
  [12, ['J', 'H', 'L']],
  [14, ['K', 'G', 'I']],
]

export const ROUND_N: Record<string, number> = {
  R32: 16, R16: 8, QF: 4, SF: 2, F: 1,
}

export const GKEYS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']
